set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

if(NOT DEFINED ENV{GITHUB_WORKSPACE})
  set(WORKSPACE "${CMAKE_CURRENT_LIST_DIR}/../..")
else()
  set(WORKSPACE "$ENV{GITHUB_WORKSPACE}")
endif()

set(CMAKE_C_COMPILER "${WORKSPACE}/ci/zig-cc-wrapper.sh")
set(CMAKE_C_COMPILER_ARG1 "aarch64-linux-musl")

set(CMAKE_CXX_COMPILER "${WORKSPACE}/ci/zig-cxx-wrapper.sh")
set(CMAKE_CXX_COMPILER_ARG1 "aarch64-linux-musl")

set(CMAKE_ASM_COMPILER "${WORKSPACE}/ci/zig-cc-wrapper.sh")
set(CMAKE_ASM_COMPILER_ARG1 "aarch64-linux-musl")

if(NOT DEFINED ZIG_EXECUTABLE)
  find_program(ZIG_EXECUTABLE zig REQUIRED)
endif()

set(CMAKE_AR "${ZIG_EXECUTABLE}" CACHE FILEPATH "Archiver")
set(CMAKE_AR_ARG1 "ar")

set(CMAKE_RANLIB "${ZIG_EXECUTABLE}" CACHE FILEPATH "Ranlib")
set(CMAKE_RANLIB_ARG1 "ranlib")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
