set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

if(NOT DEFINED ZIG_EXECUTABLE)
  find_program(ZIG_EXECUTABLE zig REQUIRED)
endif()

set(CMAKE_C_COMPILER "${ZIG_EXECUTABLE}")
set(CMAKE_C_COMPILER_ARG1 "cc")
set(CMAKE_C_COMPILER_TARGET "x86_64-linux-musl")

set(CMAKE_CXX_COMPILER "${ZIG_EXECUTABLE}")
set(CMAKE_CXX_COMPILER_ARG1 "c++")
set(CMAKE_CXX_COMPILER_TARGET "x86_64-linux-musl")

set(CMAKE_ASM_COMPILER "${ZIG_EXECUTABLE}")
set(CMAKE_ASM_COMPILER_ARG1 "cc")
set(CMAKE_ASM_COMPILER_TARGET "x86_64-linux-musl")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
